[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "td_client"
version = "0.1.0"

dependencies = [
    "pygame",
    "grpcio",
    "grpcio-tools",
    "protobuf",
    "td_shared"
]

[tool.setuptools.packages.find]
where = ["src"]
